const lightTheme = {
  '.light': {
    '--colors-brand': 'hsla(var(--palette-blue-50), 100%)',
    '--colors-body': 'hsla(var(--palette-gray-02), 100%)',
    '--colors-header': 'hsla(var(--palette-gray-02), 40%)',
    '--colors-emphasis': 'hsla(var(--palette-blue-50), 5%)',
    '--colors-foreground': 'hsla(var(--palette-gray-05), 60%)',
    '--colors-danger': 'hsla(var(--palette-red-55), 100%)',
    '--colors-danger-emphasis': 'hsla(var(--palette-red-15), 15%)',
    '--colors-warning': 'hsla(var(--palette-orange-80), 100%)',
    '--colors-warning-emphasis': 'hsla(var(--palette-orange-45), 15%)',
    '--colors-success': 'hsl(var(--palette-green-80))',
    '--colors-success-emphasis': 'hsla(var(--palette-green-45), 15%)',
    '--colors-typeface-primary': 'hsla(var(--palette-indigo-90), 100%)',
    '--colors-typeface-secondary': 'hsla(var(--palette-gray-55), 100%)',
    '--colors-typeface-tertiary': 'hsla(var(--palette-gray-60), 100%)',
    '--colors-typeface-danger': 'hsla(var(--palette-red-60), 100%)',
    '--border-color': 'var(--colors-emphasis)',
    '--card-background-color': 'hsl(var(--palette-gray-01))',
    '--form-input-active': 'var(--colors-brand)',
    '--form-input-background': 'hsl(var(--palette-gray-00))',
    '--form-input-disabled': 'hsl(var(--palette-gray-09))',
    '--form-input-border': 'hsl(var(--palette-blue-10))',
    '--form-input-focus': 'hsla(var(--palette-blue-40), 0.55)',
    '--shadow-color': 'var(--local-shadow-color, 223deg 5% 80%)',
    '--code-snippet-background': 'hsla(var(--palette-gray-03), 0.2)',
    '--token-comment': 'var(--colors-typeface-tertiary)',
    '--token-selector': 'hsl(var(--palette-indigo-50))',
    '--token-symbol': 'hsl(var(--palette-blue-60))',
    '--token-operator': 'hsl(var(--palette-orange-75))',
    '--token-keyword': 'hsl(var(--palette-blue-50))',
    '--token-function': 'hsl(var(--palette-pink-60))',
    '--token-punctuation': 'hsl(var(--palette-indigo-60))',
  },
};

export default lightTheme;
